name: build-and-deploy

on:
  workflow_dispatch:
    inputs:
      build_frontend:
        description: 'Build frontend image'
        required: true
        default: false
        type: boolean
      build_backend:
        description: 'Build backend image'
        required: true
        default: false
        type: boolean
      deploy_frontend:
        description: 'Deploy frontend image'
        required: true
        default: false
        type: boolean
      deploy_backend:
        description: 'Deploy backend image'
        required: true
        default: false
        type: boolean
      frontend_version:
        description: 'Frontend version to deploy (optional): eg: v1.0.0'
        required: false
        type: string
      backend_version:
        description: 'Backend version to deploy (optional): eg: v1.0.0'
        required: false
        type: string

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read current versions from VERSION.txt
        id: read_versions
        run: |
          FRONTEND_VERSION=$(grep "frontend=" VERSION.txt | cut -d '=' -f 2)
          BACKEND_VERSION=$(grep "backend=" VERSION.txt | cut -d '=' -f 2)
          echo "FRONTEND_VERSION=$FRONTEND_VERSION" >> $GITHUB_ENV
          echo "BACKEND_VERSION=$BACKEND_VERSION" >> $GITHUB_ENV
          
      - name: Increment frontend version
        if: ${{ github.event.inputs.build_frontend == 'true' }}
        run: |
          FRONTEND_VERSION_NO_V=$(echo ${{ env.FRONTEND_VERSION }} | sed 's/^v//')
          FRONTEND_NEW_VERSION="v$(echo $FRONTEND_VERSION_NO_V | cut -d'.' -f1).$(echo $FRONTEND_VERSION_NO_V | cut -d'.' -f2).$(($(echo $FRONTEND_VERSION_NO_V | cut -d'.' -f3) + 1))"
          echo "New frontend version: $FRONTEND_NEW_VERSION"
          echo "FRONTEND_NEW_VERSION=$FRONTEND_NEW_VERSION" >> $GITHUB_ENV

      - name: Increment backend version
        if: ${{ github.event.inputs.build_backend == 'true' }}
        run: |
          BACKEND_VERSION_NO_V=$(echo ${{ env.BACKEND_VERSION }} | sed 's/^v//')
          BACKEND_NEW_VERSION="v$(echo $BACKEND_VERSION_NO_V | cut -d'.' -f1).$(echo $BACKEND_VERSION_NO_V | cut -d'.' -f2).$(($(echo $BACKEND_VERSION_NO_V | cut -d'.' -f3) + 1))"
          echo "New backend version: $BACKEND_NEW_VERSION"
          echo "BACKEND_NEW_VERSION=$BACKEND_NEW_VERSION" >> $GITHUB_ENV

      - name: Build and push frontend image
        if: ${{ github.event.inputs.build_frontend == 'true' }}
        id: push_frontend
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/zerosandones/frontend:${{ env.FRONTEND_NEW_VERSION }} -f Dockerfile .
          docker push ghcr.io/${{ github.repository_owner }}/zerosandones/frontend:${{ env.FRONTEND_NEW_VERSION }}

      - name: Build and push backend image
        if: ${{ github.event.inputs.build_backend == 'true' }}
        id: push_backend
        run: |
          cd backend/
          docker build -t ghcr.io/${{ github.repository_owner }}/zerosandones/backend:${{ env.BACKEND_NEW_VERSION }} -f Dockerfile .
          docker push ghcr.io/${{ github.repository_owner }}/zerosandones/backend:${{ env.BACKEND_NEW_VERSION }}

      - name: Update frontend version in VERSION.txt
        if: ${{ github.event.inputs.build_frontend == 'true' && steps.push_frontend.outcome == 'success' }}
        run: |
          sed -i "s/frontend=.*/frontend=${{ env.FRONTEND_NEW_VERSION }}/" VERSION.txt
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add VERSION.txt
          git commit -m "Update frontend version to ${{ env.FRONTEND_NEW_VERSION }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

      - name: Update backend version in VERSION.txt
        if: ${{ github.event.inputs.build_backend == 'true' && steps.push_backend.outcome == 'success' }}
        run: |
          sed -i "s/backend=.*/backend=${{ env.BACKEND_NEW_VERSION }}/" VERSION.txt
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add VERSION.txt
          git commit -m "Update backend version to ${{ env.BACKEND_NEW_VERSION }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
  
  deploy_frontend:
    if: ${{ github.event.inputs.deploy_frontend == 'true' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Pull latest changes from repository
        run: git pull origin HEAD

      - name: Read frontend version from VERSION.txt
        run: |
          FRONTEND_VERSION=$(grep "frontend=" VERSION.txt | cut -d '=' -f 2)
          echo "FRONTEND_VERSION=$FRONTEND_VERSION" >> $GITHUB_ENV

      - name: Use frontend version from input or VERSION.txt
        run: |
          if [ -z "${{ github.event.inputs.frontend_version }}" ]; then
            echo "Using frontend version from VERSION.txt: ${{ env.FRONTEND_VERSION }}"
            FRONTEND_VERSION_TO_DEPLOY="${{ env.FRONTEND_VERSION }}"
          else
            echo "Using frontend version from input: ${{ github.event.inputs.frontend_version }}"
            FRONTEND_VERSION_TO_DEPLOY="${{ github.event.inputs.frontend_version }}"
          fi
          echo "FRONTEND_VERSION_TO_DEPLOY=$FRONTEND_VERSION_TO_DEPLOY" >> $GITHUB_ENV

      - name: Decode SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy frontend Docker container to production server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa  ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} << 'EOF'
            docker stop frontend-zerosandones || true
            docker rm frontend-zerosandones || true
            docker rmi $(docker images ghcr.io/${{ github.repository_owner }}/zerosandones/frontend -q) || true
            docker network inspect network-zerosandones > /dev/null 2>&1 || docker network create network-zerosandones
            docker pull ghcr.io/${{ github.repository_owner }}/zerosandones/frontend:${{ env.FRONTEND_VERSION_TO_DEPLOY }}
            docker run -d \
              --name frontend-zerosandones \
              -p 5173:5173 \
              -e VITE_ADMIN_USERNAME="${{ secrets.VITE_ADMIN_USERNAME }}" \
              -e VITE_ADMIN_PASSWORD="${{ secrets.VITE_ADMIN_PASSWORD }}" \
              --network network-zerosandones ghcr.io/${{ github.repository_owner }}/zerosandones/frontend:${{ env.FRONTEND_VERSION_TO_DEPLOY }}
            docker update --restart unless-stopped frontend-zerosandones
          EOF

      - name: Check if frontend container is running
        run: |
          echo "Checking if frontend container is running on remote server..."
          TIMEOUT=120
          START_TIME=$(date +%s)
          
          until ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} "docker ps --filter 'name=frontend-zerosandones' --filter 'status=running' --format '{{.Names}}' | grep -w 'frontend-zerosandones'"; do
            echo "Container not found or not running yet. Retrying in 5 seconds..."
            sleep 5
            
            CURRENT_TIME=$(date +%s)
            ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
            
            if [ $ELAPSED_TIME -ge $TIMEOUT ]; then
              echo "Frontend container did not start within 2 minutes. Exiting."
              exit 1
            fi
          done
          echo "frontend-zerosandones container is running!"

  deploy_backend:
    if: ${{ github.event.inputs.deploy_backend == 'true' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Pull latest changes from repository
        run: git pull origin HEAD

      - name: Read backend version from VERSION.txt
        run: |
          BACKEND_VERSION=$(grep "backend=" VERSION.txt | cut -d '=' -f 2)
          echo "BACKEND_VERSION=$BACKEND_VERSION" >> $GITHUB_ENV

      - name: Use backend version from input or VERSION.txt
        run: |
          if [ -z "${{ github.event.inputs.backend_version }}" ]; then
            echo "Using backend version from VERSION.txt: ${{ env.BACKEND_VERSION }}"
            BACKEND_VERSION_TO_DEPLOY="${{ env.BACKEND_VERSION }}"
          else
            echo "Using backend version from input: ${{ github.event.inputs.backend_version }}"
            BACKEND_VERSION_TO_DEPLOY="${{ github.event.inputs.backend_version }}"
          fi
          echo "BACKEND_VERSION_TO_DEPLOY=$BACKEND_VERSION_TO_DEPLOY" >> $GITHUB_ENV

      - name: Decode SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy backend Docker container to production server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} << 'EOF'
            docker stop backend-zerosandones || true
            docker rm backend-zerosandones  || true
            docker rmi $(docker images ghcr.io/${{ github.repository_owner }}/zerosandones/backend -q) || true
            docker network inspect network-zerosandones > /dev/null 2>&1 || docker network create network-zerosandones
            docker pull ghcr.io/${{ github.repository_owner }}/zerosandones/backend:${{ env.BACKEND_VERSION_TO_DEPLOY }}
            docker run -d \
              --name backend-zerosandones \
              --network network-zerosandones \
              -p 3000:3000 \
              -e DB_USER="${{ secrets.DB_USER }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e DB_HOST="${{ secrets.DB_HOST }}" \
              -e DB_PORT="${{ secrets.DB_PORT }}" \
              -e DB_NAME="${{ secrets.DB_NAME }}" \
              -e ADMIN_PASSWORD="${{ secrets.ADMIN_PASSWORD }}" \
              -e ALLOWED_ORIGINS="${{ secrets.ALLOWED_ORIGINS }}" \
              ghcr.io/${{ github.repository_owner }}/zerosandones/backend:${{ env.BACKEND_VERSION_TO_DEPLOY }}
            docker update --restart unless-stopped backend-zerosandones
          EOF

      - name: Check if backend container is running
        run: |
          echo "Checking if backend container is running on remote server..."
          TIMEOUT=120
          START_TIME=$(date +%s)
          
          until ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} "docker ps --filter 'name=backend-zerosandones' --filter 'status=running' --format '{{.Names}}' | grep -w 'backend-zerosandones'"; do
            echo "Container not found or not running yet. Retrying in 5 seconds..."
            sleep 5
            
            CURRENT_TIME=$(date +%s)
            ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
            
            if [ $ELAPSED_TIME -ge $TIMEOUT ]; then
              echo "Backend container did not start within 2 minutes. Exiting."
              exit 1
            fi
          done
          echo "Backend container is running!"

      - name: Clean up keys
        run: |
          rm -f ~/.ssh/id_rsa
          echo "Keys cleaned!"
